### ISSUE TITLE
Write an API document, perhaps using apiary.io

### ISSUE THREAD

**Issue by tacurran** [Aggouri/dbp-ios#2]

**Comment by Aggouri** [comment]
I think this issue should be moved to [dbpgo](https://github.com/Aggouri/dbpgo). The API description should be tied with the back-end.

**Comment by Aggouri** [comment]
Closing this issue. Opened one in [https://github.com/Aggouri/dbpgo/issues/5](https://github.com/Aggouri/dbpgo/issues/5)
